#!/usr/bin/env python3
"""One-off generator for docs/versioning/plans/*.md — run from repo root:

    python3 docs/versioning/_generate_plans.py

Refresh **INDEX.md** only (does **not** overwrite ``plans/*.md``) after editing plans by hand:

    python3 docs/versioning/_generate_plans.py --index-only
"""
from __future__ import annotations

import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PLANS = ROOT / "plans"
CHECKLIST = "../architecture/company-os-full-delivery-checklist.md"

TEMPLATE = textwrap.dedent(
    """\
    # {title}

    | Field | Value |
    |-------|-------|
    | **Version ID** | `{vid}` |
    | **Tier** | {tier} |
    | **Backlog** | [`company-os-full-delivery-checklist.md`]({checklist}) {section_ref} |

    ---

    ## 1. Goal

    {goal}

    ---

    ## 2. Prerequisites

    {prerequisites}

    ---

    ## 3. Scope

    **In scope:** {in_scope}

    **Out of scope (for this version):** {out_scope}

    ---

    ## 4. Deliverables

    {deliverables}

    ---

    ## 5. Completion confirmation (this version is *shipped*)

    Confirm each item before marking the version complete.

    {completion}

    ---

    ## 6. Working verification (this version is *proven*)

    Evidence must exist in CI, `local-prod`, or a signed reference run — not only local developer machines.

    {verification}

    ---

    ## 7. Observability & operations

    {observability}

    ---

    ## 8. Documentation & ownership

    {documentation}

    ---

    ## 9. Version sign-off

    - [ ] Sections **5** and **6** are fully satisfied with **links or run IDs** attached in your tracker.
    - [ ] No known **P0/P1** defects open against this version’s acceptance criteria.
    - [ ] **Owner** name and **date** recorded in your project system (not duplicated here).

    ---
    *Generated by `docs/versioning/_generate_plans.py` — safe to edit this file in place after generation.*
    """
)


def plan(
    vid: str,
    slug: str,
    title: str,
    tier: str,
    section_ref: str,
    goal: str,
    prerequisites: str,
    in_scope: str,
    out_scope: str,
    deliverables: str,
    completion: str,
    verification: str,
    observability: str,
    documentation: str,
) -> str:
    return TEMPLATE.format(
        vid=vid,
        title=title,
        tier=tier,
        checklist=CHECKLIST,
        section_ref=section_ref,
        goal=goal,
        prerequisites=prerequisites,
        in_scope=in_scope,
        out_scope=out_scope,
        deliverables=deliverables,
        completion=completion,
        verification=verification,
        observability=observability,
        documentation=documentation,
    )


def bullet_list(lines: list[str]) -> str:
    return "\n".join(f"- [ ] {x}" for x in lines)


NONE = "_None beyond Tier 2.1 spine and prior versions in this folder._"

VERSIONS: list[tuple[str, str, dict]] = []

# Story Tier 2.1 (14)
STORY = [
    (
        "story-01-stage1-intake",
        "OSV-STORY-01 — Stage 1 (V2) machine-runnable intake",
        {
            "tier": "2.1",
            "section": "§1 (first bullet)",
            "goal": "Automate discovery → research → question burst → doc pack in **target repo** → separate doc reviewer → `doc_review.json` → bounded revise → **plan lock** with phases, `step_id`, `depends_on`, `rollback_hint`, and contract steps.",
            "prereq": NONE,
            "in_scope": "Orchestrated intake pipeline, artifacts on disk in target repo, fail-closed gates on malformed reviewer output.",
            "out": "Implementation execution (Stage 3); parallel lanes (Stage 2 full V7).",
            "deliv": bullet_list(
                [
                    "`discovery.json` (or equivalent) schema-valid",
                    "`research_digest.md` + question artifacts",
                    "Doc pack paths declared and written",
                    "`doc_review.json` with pass/fail + findings",
                    "Locked `project_plan.json` with contract steps",
                ]
            ),
            "done": bullet_list(
                [
                    "Golden-repo demo: cold start → plan lock without manual file edits",
                    "Reviewer identity separate from planner in config + audit log",
                    "Revise loop respects max retries; surfaces `blocked_human` when exhausted",
                ]
            ),
            "verify": bullet_list(
                [
                    "Automated test: invalid `doc_review.json` rejected",
                    "CI job: intake golden path < N minutes wall clock (budget declared)",
                    "Trace: every artifact hash referenced from `session_events` or platform event stub",
                ]
            ),
            "obs": "`doc_review` latency + retry counts dashboarded or logged structurally.",
            "doc": "`docs/runbooks/` intake failure modes + `docs/adrs/` for schema choices.",
        },
    ),
    (
        "story-02-learning-first-profile",
        "OSV-STORY-02 — LearningFirstProfile (V2)",
        {
            "tier": "2.1",
            "section": "§1 (LearningFirstProfile)",
            "goal": "Enforce a **minimum** count of `learning_events.jsonl` entries by plan lock (e.g. plan-lock floor), not advisory-only text.",
            "prereq": "OSV-STORY-01 (plan lock emits learning hooks).",
            "in_scope": "Counters, hard-stop or gate when floor unmet, deterministic event shapes.",
            "out": "Cross-run reflection (OSV-STORY-11) except minimum event contract.",
            "deliv": bullet_list(
                [
                    "Config: `learning_first_min_events` (name may vary) documented",
                    "Gate module rejects plan lock when floor unmet",
                    "Sample `learning_events.jsonl` lines schema-valid",
                ]
            ),
            "done": bullet_list(
                [
                    "Intake run below floor **fails closed** with clear code + user message",
                    "Run above floor succeeds with counted events in manifest",
                ]
            ),
            "verify": bullet_list(
                [
                    "Unit tests: boundary at floor-1, floor, floor+1",
                    "Property or table test on event shape",
                ]
            ),
            "obs": "Metric: `learning_events_total_at_plan_lock`.",
            "doc": "Update action-plan cross-ref; document env defaults.",
        },
    ),
    (
        "story-03-parallel-lanes",
        "OSV-STORY-03 — True parallel lanes (V7 Stage 2)",
        {
            "tier": "2.1",
            "section": "§1 (parallel lanes)",
            "goal": "Dependency-grouped workstreams run **concurrently** with per-lane queues and bounded `max_concurrent_agents` — not only sequential project driver + optional worktrees.",
            "prereq": "OSV-STORY-01; OSV-STORY-04 recommended.",
            "in_scope": "Scheduler, lane model, concurrency cap, integration with step issuance.",
            "out": "Full IAM federation (covered in ladder V7 + services).",
            "deliv": bullet_list(
                [
                    "Lane scheduler module + config surface",
                    "Proof: two lanes make progress overlapping in wall time",
                    "`max_concurrent_agents` enforced under load",
                ]
            ),
            "done": bullet_list(
                [
                    "Stress run: N steps, M lanes, no duplicate `step_id` execution",
                    "Back-pressure when cap reached (queue depth observable)",
                ]
            ),
            "verify": bullet_list(
                [
                    "Integration test with synthetic slow steps proves overlap",
                    "Chaos-lite: one lane slow does not deadlock others when deps allow",
                ]
            ),
            "obs": "Per-lane throughput, queue wait p95, scheduler errors.",
            "doc": "Runbook: lane starvation + cap tuning.",
        },
    ),
    (
        "story-04-leases-heartbeats",
        "OSV-STORY-04 — Leases + heartbeats",
        {
            "tier": "2.1",
            "section": "§1 (leases + heartbeats)",
            "goal": "Lease grant/renew/expiry; heartbeat timeout → reassignment or `blocked_human`; **all** file mutations checked against lease (not prompt-only).",
            "prereq": "OSV-STORY-07 (orchestrated writes) strongly coupled.",
            "in_scope": "Lease table authority, heartbeat protocol, orchestrator enforcement hook.",
            "out": "Multi-tenant IAM (OSV-EXTRACT-02).",
            "deliv": bullet_list(
                [
                    "`lease_table` durable representation + API",
                    "Heartbeat tick + staleness policy",
                    "Write path rejects out-of-lease paths with machine-readable error",
                ]
            ),
            "done": bullet_list(
                [
                    "Attempted write outside lease **never** reaches filesystem",
                    "Expired lease transitions logged with actor + reason",
                ]
            ),
            "verify": bullet_list(
                [
                    "Security test: lease escape attempts",
                    "Time-budget test: forced heartbeat miss triggers reassignment path",
                ]
            ),
            "obs": "Lease violations counter; heartbeat miss rate.",
            "doc": "Threat-model update for lease authority.",
        },
    ),
    (
        "story-05-contract-step-gating",
        "OSV-STORY-05 — Contract-step gating between lanes",
        {
            "tier": "2.1",
            "section": "§1 (contract steps)",
            "goal": "Shared API/DB/schema **contract steps** block dependent lanes until review + verification evidence exists.",
            "prereq": "OSV-STORY-01; OSV-STORY-03.",
            "in_scope": "Dependency graph respects `contract` step kind; blocking semantics.",
            "out": "Durable global policy engine (service tier).",
            "deliv": bullet_list(
                [
                    "Plan schema: contract steps typed and validated",
                    "Scheduler refuses lane start until contract evidence recorded",
                    "Evidence artifact paths referenced in traces",
                ]
            ),
            "done": bullet_list(
                [
                    "Demo: frontend lane blocked until API contract step green",
                ]
            ),
            "verify": bullet_list(
                [
                    "Integration: mis-ordered start attempt fails",
                    "Graph unit tests on complex DAG",
                ]
            ),
            "obs": "Blocked-on-contract duration metric.",
            "doc": "Authoring guide for plan authors.",
        },
    ),
    (
        "story-06-separation-of-duties",
        "OSV-STORY-06 — Separation of duties (roles)",
        {
            "tier": "2.1",
            "section": "§1 (SoD)",
            "goal": "Implementor cannot approve; Reviewer always separate model call/role/credentials; Planner cannot self-approve docs.",
            "prereq": "OSV-STORY-01.",
            "in_scope": "Role binding per RPC, token/credential separation, audit trail.",
            "out": "Full `identity-authz` service (OSV-SVC-identity-authz).",
            "deliv": bullet_list(
                [
                    "Role registry in orchestrator config",
                    "Enforcement at API boundary (not only prompts)",
                    "Audit: `actor_role` on each approval event",
                ]
            ),
            "done": bullet_list(
                [
                    "Negative test: same credential cannot call reviewer + implementor paths",
                ]
            ),
            "verify": bullet_list(
                [
                    "Security tests for role confusion",
                    "Replay audit proves separation on golden run",
                ]
            ),
            "obs": "SoD violation attempts alert or counter.",
            "doc": "ADR: credential model.",
        },
    ),
    (
        "story-07-orchestrated-writes",
        "OSV-STORY-07 — Orchestrated writes",
        {
            "tier": "2.1",
            "section": "§1 (orchestrated writes)",
            "goal": "All implementation writes go through orchestrator APIs enforcing lease + trace + gate order.",
            "prereq": "OSV-STORY-04.",
            "in_scope": "Filesystem adapter behind API; deny direct agent FS access in prod profile.",
            "out": "Sandbox worker execution (OSV-WORKER-*).",
            "deliv": bullet_list(
                [
                    "`apply_patch` / `write_file` RPC (names illustrative)",
                    "Pre-write gate chain hook",
                    "Trace event per successful write",
                ]
            ),
            "done": bullet_list(
                [
                    "No code path bypasses API for writes in `local-prod`",
                ]
            ),
            "verify": bullet_list(
                [
                    "Static check or integration: grep-proof + runtime bypass test fails",
                ]
            ),
            "obs": "Write volume, rejection reasons.",
            "doc": "Developer guide: adding new write types.",
        },
    ),
    (
        "story-08-per-step-review-loop",
        "OSV-STORY-08 — Per-step review loop",
        {
            "tier": "2.1",
            "section": "§1 (per-step review)",
            "goal": "`step_reviews/<step_id>.json` with findings, evidence refs, bounded retries, remediation / blocked_human on critical path.",
            "prereq": "OSV-STORY-06; OSV-STORY-07.",
            "in_scope": "Reviewer pipeline, retry caps, progress rules.",
            "out": "Full evaluation service scoring.",
            "deliv": bullet_list(
                [
                    "Schema for step review + examples",
                    "Critical-path detection for `blocked_human`",
                    "Progress advance rules wired",
                ]
            ),
            "done": bullet_list(
                [
                    "Golden run exhausts retries → expected terminal state",
                ]
            ),
            "verify": bullet_list(
                [
                    "Unit tests on retry / critical path matrix",
                ]
            ),
            "obs": "Reviewer pass rate, retries per step.",
            "doc": "Checklist for human escalation.",
        },
    ),
    (
        "story-09-verification-from-plan",
        "OSV-STORY-09 — Verification from plan (Stage 4)",
        {
            "tier": "2.1",
            "section": "§1 (verification from plan)",
            "goal": "Commands from plan metadata; `verification_logs/`; `verification_bundle.json` drives pass/fail and failure attribution loop to Stage 3.",
            "prereq": "OSV-STORY-01; OSV-STORY-08.",
            "in_scope": "Command runner, log capture, bundle schema, attribution heuristic or model-assisted with bounds.",
            "out": "Remote sandbox execution.",
            "deliv": bullet_list(
                [
                    "Plan fields for commands declared and validated",
                    "Log paths + redaction policy",
                    "Attribution output ties failure to `step_id`",
                ]
            ),
            "done": bullet_list(
                [
                    "Failing command triggers re-entry to implementor with captured logs",
                ]
            ),
            "verify": bullet_list(
                [
                    "Integration with fake failing test command",
                ]
            ),
            "obs": "Verification duration, flake rate.",
            "doc": "Runbook: command allowlist.",
        },
    ),
    (
        "story-10-dod-automation",
        "OSV-STORY-10 — Definition-of-done automation (Stage 5)",
        {
            "tier": "2.1",
            "section": "§1 (DoD)",
            "goal": "DoD items checked by code; terminal status cannot lie (HS15-class honesty end-to-end).",
            "prereq": "OSV-STORY-08; OSV-STORY-09.",
            "in_scope": "DoD schema, evaluators per item, terminal state machine.",
            "out": "UI dashboard.",
            "deliv": bullet_list(
                [
                    "`definition_of_done.json` evaluators implemented",
                    "Terminal states enumerated; illegal transitions rejected",
                ]
            ),
            "done": bullet_list(
                [
                    "Cannot emit `completed_review_pass` with any red DoD item",
                ]
            ),
            "verify": bullet_list(
                [
                    "Table tests for DoD combinations",
                ]
            ),
            "obs": "DoD failure reasons histogram.",
            "doc": "DoD authoring for plan templates.",
        },
    ),
    (
        "story-11-cross-run-learning-v6",
        "OSV-STORY-11 — Cross-run learning (V6 operational)",
        {
            "tier": "2.1",
            "section": "§1 (Stage 6 V6)",
            "goal": "Reflection with causal closure, practice from skill gaps, canary shadow runs, promotion with independent evaluator — durable and policy-gated.",
            "prereq": "OSV-SVC-memory-lifecycle; OSV-SVC-learning-update; policy paths.",
            "in_scope": "Pipelines + storage + gates tying to HS25–HS28 semantics.",
            "out": "Full canary-rollout service autoscaler.",
            "deliv": bullet_list(
                [
                    "Durable artifacts + services wired",
                    "Policy: who may promote what",
                ]
            ),
            "done": bullet_list(
                [
                    "Run A failure → Run B shows measurable different decision with provenance",
                ]
            ),
            "verify": bullet_list(
                [
                    "Promotion tests + canary shadow diff tests",
                ]
            ),
            "obs": "Canary error budget; promotion latency.",
            "doc": "Learning governance ADR.",
        },
    ),
    (
        "story-12-durable-event-platform",
        "OSV-STORY-12 — Durable event platform (Stage 7 / V4)",
        {
            "tier": "both",
            "section": "§1 + §2 V4",
            "goal": "Append-only event store, envelopes, integrity, fail-closed replay, kill switch as platform events — beyond per-run `traces.jsonl` only.",
            "prereq": "OSV-CONTRACTS-01; OSV-SVC-event-store.",
            "in_scope": "Platform event ingest, retention, replay API.",
            "out": "Global multi-region scaling (document as future if needed).",
            "deliv": bullet_list(
                [
                    "Event envelope schema deployed",
                    "Replay job + manifest mismatch = fail",
                    "Kill switch event type + ACL",
                ]
            ),
            "done": bullet_list(
                [
                    "Tampered stream rejected in CI replay test",
                ]
            ),
            "verify": bullet_list(
                [
                    "Golden replay suite on durable store",
                ]
            ),
            "obs": "Ingest lag, replay duration, integrity failures.",
            "doc": "Event catalog.",
        },
    ),
    (
        "story-13-durable-memory-v5",
        "OSV-STORY-13 — Durable memory (Stage 8 / V5)",
        {
            "tier": "both",
            "section": "§1 + §2 V5",
            "goal": "Episodic + semantic + skill stores; retrieval/write policies; quarantine; decay/recertification; provenance on every retrieve used in decisions.",
            "prereq": "OSV-SVC-memory-lifecycle; OSV-LIB-memory-sdk.",
            "in_scope": "Memory APIs, quarantine workflow, orchestrator retrieve hooks.",
            "out": "ML embedding model training.",
            "deliv": bullet_list(
                [
                    "Store backends configured in `local-prod`",
                    "Quarantine UX or API for operators",
                    "Provenance fields on planner context packs",
                ]
            ),
            "done": bullet_list(
                [
                    "Contradicting memories do not merge silently",
                ]
            ),
            "verify": bullet_list(
                [
                    "HS21–HS24 conformance tests against service",
                ]
            ),
            "obs": "Retrieve hit rate, quarantine queue depth.",
            "doc": "Memory hygiene runbook.",
        },
    ),
    (
        "story-14-continuous-cto-gates",
        "OSV-STORY-14 — Continuous CTO gates (platform-wide)",
        {
            "tier": "2.1",
            "section": "§1 (continuous gates)",
            "goal": "Token/context/refusal/retry on every LLM call; hard-stop sweeps at stage boundaries; composite balanced gates block `completed_review_pass` when subscores fail.",
            "prereq": "Story versions through DoD; ladder V1 baseline.",
            "in_scope": "Central gate dispatcher + hooks at all stage boundaries + LLM client wrapper.",
            "out": "New HS beyond published set without ADR.",
            "deliv": bullet_list(
                [
                    "Wrapper on all model providers",
                    "Stage boundary sweep registry",
                    "Composite score evaluator",
                ]
            ),
            "done": bullet_list(
                [
                    "Every public API path documented with gate list",
                ]
            ),
            "verify": bullet_list(
                [
                    "Mutation tests on gate order",
                    "Fuzz on refusal payloads",
                ]
            ),
            "obs": "Gate failure reasons; token histograms.",
            "doc": "Gate matrix published.",
        },
    ),
]

LADDER = []
for i, (hs, name) in enumerate(
    [
        ("HS01–HS06", "V1 — execution trust on all run classes"),
        ("HS07–HS12", "V2 — planning hard-stops on real artifacts"),
        ("HS13–HS16", "V3 — completion / verify / DoD"),
        ("HS17–HS20", "V4 — durable lineage + replay"),
        ("HS21–HS24", "V5 — durable memory"),
        ("HS25–HS28", "V6 — operational learning loop"),
        ("HS29–HS32", "V7 — live multi-agent + IAM"),
    ],
    start=1,
):
    slug = f"ladder-{i:02d}-v{i}"
    LADDER.append(
        (
            slug,
            f"OSV-LADDER-{i:02d} — {name}",
            {
                "tier": "2.1 / 2.2",
                "section": f"§2 (V{i})",
                "goal": f"Prove `{hs}` against **real** platform behavior and artifacts — not scaffold-only JSON under `outputs/` where the checklist requires durability or live coordination.",
                "prereq": "Cross-reference story versions that supply artifacts for this ladder slice.",
                "in_scope": f"Conformance suite mapping each stop in {hs}; evidence in CI.",
                "out": "Optional stricter policies not in published HS set.",
                "deliv": bullet_list(
                    [
                        f"HS mapping table for {hs} linked to tests",
                        "Golden manifests + expected pass/fail",
                        "CI job name declared",
                    ]
                ),
                "done": bullet_list(
                    [
                        "All mapped stops green on reference profile",
                        "Failure injectors prove fail-closed paths per stop",
                    ]
                ),
                "verify": bullet_list(
                    [
                        "Dedicated test module or job id referenced in README",
                        "Coverage report attached for HS paths",
                    ]
                ),
                "obs": f"Per-stop counters for {hs} in observability stack when available.",
                "doc": f"Update checklist §2 V{i} with links to evidence.",
            },
        )
    )

CONTRACTS = [
    (
        "contracts-01-tree",
        "OSV-CONTRACTS-01 — `src/contracts/` published schemas",
        {
            "tier": "2.2",
            "section": "§3 (tree)",
            "goal": "Populate versioned JSON/YAML contracts for event, policy, lifecycle, capability, authz, RPC — not Python-only ad-hoc shapes.",
            "prereq": NONE,
            "in_scope": "Directory layout, semver per contract family, publishing.",
            "out": "Implementing all services (separate versions).",
            "deliv": bullet_list(
                [
                    "All contract files listed in manifest",
                    "Consumers import by version pin",
                ]
            ),
            "done": bullet_list(["Contract manifest CI green"]),
            "verify": bullet_list(
                ["Validator rejects unknown fields where policy says strict"]
            ),
            "obs": "Contract validation failures.",
            "doc": "Contract README index.",
        },
    ),
    (
        "contracts-02-policy-activation",
        "OSV-CONTRACTS-02 — Objective arbitration & policy bundle activation path",
        {
            "tier": "2.2",
            "section": "§3",
            "goal": "Single-owner activation of objective arbitration + policy bundles through `policy-management` semantics.",
            "prereq": "OSV-CONTRACTS-01; OSV-SVC-policy-management.",
            "in_scope": "Schemas + RPC + enforcement proof.",
            "out": "Policy editor UI.",
            "deliv": bullet_list(["Activation audit event", "Rollback path"]),
            "done": bullet_list(["Bypass attempt fails in test"]),
            "verify": bullet_list(["Integration with policy-management only mutator"]),
            "obs": "Activation rate, rollback count.",
            "doc": "Policy lifecycle ADR.",
        },
    ),
    (
        "contracts-03-authz-matrix",
        "OSV-CONTRACTS-03 — Role/stage/risk matrix & approval tokens",
        {
            "tier": "2.2",
            "section": "§3",
            "goal": "Enforce role/stage/risk matrix + approval tokens on high-risk actions via `identity-authz`.",
            "prereq": "OSV-CONTRACTS-01; OSV-SVC-identity-authz.",
            "in_scope": "Token format, validation, replay resistance.",
            "out": "Hardware security modules.",
            "deliv": bullet_list(["Matrix versioned", "Token issue/revoke APIs"]),
            "done": bullet_list(["High-risk RPC without token = 403"]),
            "verify": bullet_list(["Security suite: replay, scope creep"]),
            "obs": "Authz denials.",
            "doc": "Threat model update.",
        },
    ),
    (
        "contracts-04-lint",
        "OSV-CONTRACTS-04 — Contract lint CI (`tools/contract-lint`)",
        {
            "tier": "2.2",
            "section": "§3",
            "goal": "Fail-closed CI on breaking contract changes without version bump + migration story.",
            "prereq": "OSV-CONTRACTS-01.",
            "in_scope": "Lint rules, CI wiring, reporting.",
            "out": "Auto-fix of contracts.",
            "deliv": bullet_list(["CLI tool", "CI job"]),
            "done": bullet_list(["Breaking diff fails PR"]),
            "verify": bullet_list(["Golden breaking PR test in fixtures"]),
            "obs": "Lint failures by rule.",
            "doc": "Contributor guide.",
        },
    ),
    (
        "contracts-05-upcaster",
        "OSV-CONTRACTS-05 — Schema upcaster tool",
        {
            "tier": "2.2",
            "section": "§3",
            "goal": "Supported upgrade paths for contract versions (`tools/schema-upcaster`).",
            "prereq": "OSV-CONTRACTS-01; OSV-CONTRACTS-04.",
            "in_scope": "Declared migrations N→N+1, tests per migration.",
            "out": "Arbitrary version jumps without matrix.",
            "deliv": bullet_list(["Upcast table", "Tests"]),
            "done": bullet_list(["Each supported jump has test data"]),
            "verify": bullet_list(["CI migrates golden fixtures"]),
            "obs": "Upcast failures.",
            "doc": "Versioning policy.",
        },
    ),
]

SERVICES = [
    "objective-policy-engine",
    "lifecycle-governance",
    "identity-authz",
    "policy-management",
    "event-store",
    "projection-query",
    "memory-lifecycle",
    "capability-graph",
    "reflection-rca",
    "learning-update",
    "canary-rollout",
    "evaluation",
    "safety-controller",
    "model-router",
    "quota-scheduler",
    "observability-gateway",
    "incident-ops",
    "chaos-simulator",
]

ORCH = [
    (
        "orch-01-service-rpc",
        "OSV-ORCH-01 — Inter-service RPC (`common_rpc.v1`)",
        {
            "tier": "2.2",
            "section": "§5",
            "goal": "All cross-service calls use published RPC contract with timeouts, auth, and tracing.",
            "prereq": "OSV-CONTRACTS-01.",
            "in_scope": "Client libs, server stubs, tracing propagation.",
            "out": "Alternate transports beyond chosen default.",
            "deliv": bullet_list(["RPC catalog", "Example service pair"]),
            "done": bullet_list(["No raw HTTP between services without contract"]),
            "verify": bullet_list(["Contract tests for RPC payloads"]),
            "obs": "RPC error rate, latency p95.",
            "doc": "RPC standards ADR.",
        },
    ),
    (
        "orch-02-hierarchy-deadlock",
        "OSV-ORCH-02 — Hierarchy + deadlock handling",
        {
            "tier": "2.2",
            "section": "§5",
            "goal": "`hierarchy.v1` + `deadlock.v1` behaviors proven under multi-lane load.",
            "prereq": "OSV-STORY-03.",
            "in_scope": "Detection, logging, recovery or safe stall.",
            "out": "Distributed consensus across regions.",
            "deliv": bullet_list(["State machine", "Tests with cyclic deps"]),
            "done": bullet_list(["No silent deadlock > T seconds"]),
            "verify": bullet_list(["Chaos: slow dependency injection"]),
            "obs": "Deadlock detection signals.",
            "doc": "Runbook: operator recovery.",
        },
    ),
    (
        "orch-03-platform-scheduler",
        "OSV-ORCH-03 — Platform orchestrator + global precedence",
        {
            "tier": "2.2",
            "section": "§5",
            "goal": "Orchestrator routes work across services/agents with action-plan §5 precedence enforced in code.",
            "prereq": "OSV-ORCH-01; OSV-SVC-* integrations.",
            "in_scope": "Precedence table, conflict resolution, audit.",
            "out": "Human workflow UI.",
            "deliv": bullet_list(["Precedence module", "Integration tests"]),
            "done": bullet_list(["Lower priority never bypasses safety veto"]),
            "verify": bullet_list(["Matrix test of precedence vs injected failures"]),
            "obs": "Precedence violation counter = 0.",
            "doc": "Precedence published for operators.",
        },
    ),
]

WORKER = [
    (
        "worker-01-image",
        "OSV-WORKER-01 — Deterministic worker image / build pipeline",
        {
            "tier": "2.2",
            "section": "§6",
            "goal": "Reproducible worker artifact with pinned deps and checksum publication.",
            "prereq": NONE,
            "in_scope": "Dockerfile or equivalent, CI build, SBOM optional.",
            "out": "Multi-arch beyond agreed matrix.",
            "deliv": bullet_list(["Image registry or local tar", "Version tag policy"]),
            "done": bullet_list(["Repro build: same digest from same inputs"]),
            "verify": bullet_list(["CI rebuild == digest"]),
            "obs": "Build failures.",
            "doc": "Worker release process.",
        },
    ),
    (
        "worker-02-sandbox",
        "OSV-WORKER-02 — Isolated sandbox execution",
        {
            "tier": "2.2",
            "section": "§6",
            "goal": "Code/tests run inside container (or equivalent) with resource limits.",
            "prereq": "OSV-WORKER-01.",
            "in_scope": "Job API, mount policy, network policy.",
            "out": "GPU scheduling.",
            "deliv": bullet_list(["Sandbox contract", "Escape tests"]),
            "done": bullet_list(["Known escape vectors mitigated or documented accepted risk"]),
            "verify": bullet_list(["Security: egress denial tests"]),
            "obs": "Sandbox OOM kills, wall time.",
            "doc": "Sandbox threat model.",
        },
    ),
    (
        "worker-03-policies",
        "OSV-WORKER-03 — Worker policy enforcement",
        {
            "tier": "2.2",
            "section": "§6",
            "goal": "CPU/mem/disk/network/fs egress policies injected per job class.",
            "prereq": "OSV-WORKER-02.",
            "in_scope": "Policy schema + enforcement + violations.",
            "out": "Per-tenant custom unlimited policy.",
            "deliv": bullet_list(["Policy profiles", "Violation telemetry"]),
            "done": bullet_list(["Over-limit job killed with reason"]),
            "verify": bullet_list(["Resource exhaustion tests"]),
            "obs": "Policy violation reasons.",
            "doc": "Policy catalog.",
        },
    ),
    (
        "worker-04-remote-runtimes",
        "OSV-WORKER-04 — Remote / optional runtimes productized",
        {
            "tier": "2.2",
            "section": "§6",
            "goal": "Non–local-Mac-only honest execution path where architecture requires remote runtime.",
            "prereq": "OSV-WORKER-02.",
            "in_scope": "Provider adapter, credentials, quotas.",
            "out": "Full multi-cloud marketplace.",
            "deliv": bullet_list(["Adapter interface", "One provider E2E"]),
            "done": bullet_list(["Reference task passes on remote path"]),
            "verify": bullet_list(["Failover test if multi-provider"]),
            "obs": "Remote latency, cost estimate.",
            "doc": "Remote runtime runbook.",
        },
    ),
]

AGENTS = [
    (
        "agent-01-implementation-ladder",
        "OSV-AGENT-01 — Implementation agents (junior → architect)",
        {
            "tier": "2.2",
            "section": "§7",
            "goal": "Distinct deployable/configurable packages for junior, midlevel, senior, architect personas with capability boundaries.",
            "prereq": "OSV-ORCH-01; OSV-SVC-capability-graph.",
            "in_scope": "Prompt/tool bundles, RPC surfaces, certification hooks.",
            "out": "Fine-tuned proprietary weights.",
            "deliv": bullet_list(["Four packages or modules with README", "Certification state integration"]),
            "done": bullet_list(["Each role refuses out-of-band actions in tests"]),
            "verify": bullet_list(["Role matrix tests"]),
            "obs": "Role usage counts.",
            "doc": "Role guide.",
        },
    ),
    (
        "agent-02-reviewer",
        "OSV-AGENT-02 — Reviewer agent (isolated credentials)",
        {
            "tier": "2.2",
            "section": "§7",
            "goal": "Reviewer cannot share implementor credentials or bypass gates.",
            "prereq": "OSV-AGENT-01; OSV-STORY-06.",
            "in_scope": "Separate deployment, token scope, audit.",
            "out": "Human reviewer UI.",
            "deliv": bullet_list(["Reviewer service/package", "Credential separation proof"]),
            "done": bullet_list(["SoD tests green"]),
            "verify": bullet_list(["Pen test checklist"]),
            "obs": "Reviewer latency.",
            "doc": "Reviewer playbook.",
        },
    ),
    (
        "agent-03-evaluator",
        "OSV-AGENT-03 — Evaluator agent",
        {
            "tier": "2.2",
            "section": "§7",
            "goal": "Independent evaluation signals for promotion / quality gates.",
            "prereq": "OSV-SVC-evaluation.",
            "in_scope": "Evaluator RPC, rubrics, conflict with implementor.",
            "out": "LLM-as-judge without human appeal path.",
            "deliv": bullet_list(["Rubric schema", "Sample eval run"]),
            "done": bullet_list(["Evaluator disagrees implementor in controlled fixture"]),
            "verify": bullet_list(["Statistical stability on golden set if applicable"]),
            "obs": "Eval agreement rate.",
            "doc": "Eval methodology.",
        },
    ),
    (
        "agent-04-learning-practice",
        "OSV-AGENT-04 — Learning & practice agents",
        {
            "tier": "2.2",
            "section": "§7",
            "goal": "Learning-agent + practice-agent drive structured capture and drills.",
            "prereq": "OSV-SVC-learning-update; OSV-STORY-11.",
            "in_scope": "Triggers, outputs, gates.",
            "out": "Automatic curriculum generation from web scrape.",
            "deliv": bullet_list(["Agent packages", "Event subscriptions"]),
            "done": bullet_list(["Practice task created from detected gap"]),
            "verify": bullet_list(["End-to-end gap→practice test"]),
            "obs": "Practice completion rate.",
            "doc": "Learning ethics boundaries.",
        },
    ),
    (
        "agent-05-manager-specialist-career",
        "OSV-AGENT-05 — Manager, specialist, career-strategy agents",
        {
            "tier": "2.2",
            "section": "§7",
            "goal": "Org-facing agents for delegation, depth, and career guidance within policy.",
            "prereq": "OSV-SVC-quota-scheduler; OSV-SVC-objective-policy-engine.",
            "in_scope": "RPC + governance + human escalation paths.",
            "out": "HRIS integration.",
            "deliv": bullet_list(["Three packages", "Escalation contracts"]),
            "done": bullet_list(["Agents cannot override safety veto"]),
            "verify": bullet_list(["Policy matrix tests"]),
            "obs": "Escalation volume.",
            "doc": "Org agent charter.",
        },
    ),
    (
        "agent-06-career-wiring",
        "OSV-AGENT-06 — Career / progression / recertification / stagnation wiring",
        {
            "tier": "2.2",
            "section": "§7 (last bullet)",
            "goal": "Master-doc career flows wired to capability-graph + lifecycle-governance with measurable signals.",
            "prereq": "OSV-SVC-capability-graph; OSV-SVC-lifecycle-governance; OSV-AGENT-05.",
            "in_scope": "State transitions, metrics, alerts on stagnation.",
            "out": "Legal compliance for employment domains.",
            "deliv": bullet_list(["Transition table", "Metrics pipeline"]),
            "done": bullet_list(["Demo promotion/demotion with audit"]),
            "verify": bullet_list(["Invalid transition rejected"]),
            "obs": "Stagnation alerts.",
            "doc": "Career policy ADR.",
        },
    ),
]

LIBS = [
    ("lib-01-event-sdk", "OSV-LIB-01 — event-sdk", "Event produce/consume helpers aligned to contracts."),
    ("lib-02-contract-validator", "OSV-LIB-02 — contract-validator", "Runtime + CI validation shared library."),
    ("lib-03-lineage-sdk", "OSV-LIB-03 — lineage-sdk", "Lineage and replay helpers for callers."),
    ("lib-04-policy-eval-sdk", "OSV-LIB-04 — policy-eval-sdk", "Policy evaluation helpers for services."),
    ("lib-05-memory-sdk", "OSV-LIB-05 — memory-sdk", "Memory read/write with provenance helpers."),
]

DATA = [
    (
        "data-01-seed-curriculum",
        "OSV-DATA-01 — seed-curriculum",
        {
            "tier": "2.2",
            "section": "§8",
            "goal": "Managed, versioned curriculum content for training/eval agents.",
            "prereq": NONE,
            "in_scope": "Repo layout, versioning, validation.",
            "out": "Licensed third-party courseware ingestion.",
            "deliv": bullet_list(["Version tags", "Validation CI"]),
            "done": bullet_list(["Consumers pin curriculum version"]),
            "verify": bullet_list(["Schema tests on curriculum entries"]),
            "obs": "Curriculum usage.",
            "doc": "Curriculum contribution guide.",
        },
    ),
    (
        "data-02-benchmark-suites",
        "OSV-DATA-02 — benchmark-suites (product versioning)",
        {
            "tier": "2.2",
            "section": "§8",
            "goal": "Benchmark suites beyond ad-hoc jsonl: semantic versioning + changelog.",
            "prereq": "OSV-SVC-evaluation.",
            "in_scope": "Suite registry, compatibility matrix with runner.",
            "out": "Paid benchmark marketplace.",
            "deliv": bullet_list(["Suite manifest", "Runner integration"]),
            "done": bullet_list(["CI references suite by version"]),
            "verify": bullet_list(["Regression on suite upgrade path"]),
            "obs": "Pass rate per suite version.",
            "doc": "Suite authoring standard.",
        },
    ),
    (
        "data-03-replay-manifests-catalog",
        "OSV-DATA-03 — replay-manifests catalog",
        {
            "tier": "2.2",
            "section": "§8",
            "goal": "Catalog of replay manifests tied to durable event store.",
            "prereq": "OSV-STORY-12; OSV-SVC-event-store.",
            "in_scope": "Index, retention, access control.",
            "out": "Public anonymous replay.",
            "deliv": bullet_list(["Catalog API", "Retention policy"]),
            "done": bullet_list(["Golden replays discoverable by id"]),
            "verify": bullet_list(["Integrity check job"]),
            "obs": "Catalog query latency.",
            "doc": "Replay retention policy.",
        },
    ),
]

INFRA = [
    (
        "infra-01-local-prod-profile",
        "OSV-INFRA-01 — `local-prod` profile complete",
        {
            "tier": "2.2",
            "section": "§9",
            "goal": "Storage bindings, secrets, backups, monitoring dashboards, SLOs/alerts as code for local-prod.",
            "prereq": "Core services deployed.",
            "in_scope": "IaC or checked-in configs, secrets handling.",
            "out": "Multi-region prod.",
            "deliv": bullet_list(["Profile directory", "Dashboards", "Alert rules"]),
            "done": bullet_list(["`local-prod up` or equivalent documented one-shot"]),
            "verify": bullet_list(["Smoke: all health endpoints green"]),
            "obs": "SLO burn rates.",
            "doc": "`docs/runbooks/local-prod.md`.",
        },
    ),
    (
        "infra-02-backup-restore-drills",
        "OSV-INFRA-02 — Backup / restore exercised",
        {
            "tier": "2.2",
            "section": "§9",
            "goal": "Backup-restore runbooks **drilled** with evidence (dates, logs).",
            "prereq": "OSV-INFRA-01.",
            "in_scope": "RPO/RTO targets, drill checklist.",
            "out": "Continuous backup to cold storage vendor beyond chosen one.",
            "deliv": bullet_list(["Drill report template", "Last drill log link"]),
            "done": bullet_list(["Successful restore to clean env"]),
            "verify": bullet_list(["Automated restore test in staging"]),
            "obs": "Backup failures.",
            "doc": "Restore runbook.",
        },
    ),
    (
        "infra-03-storage-pinned",
        "OSV-INFRA-03 — Master-doc storage choices pinned & operated",
        {
            "tier": "2.2",
            "section": "§9",
            "goal": "Architecture §15-class storage decisions bound and running, not deferred.",
            "prereq": "OSV-INFRA-01.",
            "in_scope": "DB/object/event retention choices, capacity planning.",
            "out": "Exotic experimental stores.",
            "deliv": bullet_list(["ADRs for each store", "Ops dashboards"]),
            "done": bullet_list(["No TODO for primary persistence in prod profile"]),
            "verify": bullet_list(["Failover or restore test per store class"]),
            "obs": "Disk growth forecasts.",
            "doc": "Storage map.",
        },
    ),
]

PRODUCT = [
    (
        "product-01-ui-dashboard",
        "OSV-PRODUCT-01 — UI / dashboard",
        {
            "tier": "2.2",
            "section": "§10",
            "goal": "If in-product: UI for runs, lanes, memory quarantine, promotions, incidents.",
            "prereq": "OSV-SVC-observability-gateway; relevant backends.",
            "in_scope": "AuthN/Z for UI, core views, audit.",
            "out": "Mobile native apps.",
            "deliv": bullet_list(["Deployed UI", "E2E tests"]),
            "done": bullet_list(["Role-based access matches API"]),
            "verify": bullet_list(["Playwright or equivalent suite"]),
            "obs": "UI errors, Core Web Vitals if web.",
            "doc": "User guide.",
        },
    ),
    (
        "product-02-operator-runbooks",
        "OSV-PRODUCT-02 — Operator runbooks in sync",
        {
            "tier": "2.2",
            "section": "§10",
            "goal": "`docs/runbooks/` reflects every shipped failure mode and recovery path.",
            "prereq": "Features they document must exist.",
            "in_scope": "Runbook index, owners, review dates.",
            "out": "Video training library.",
            "deliv": bullet_list(["Runbook per P0 scenario", "Quarterly review tick"]),
            "done": bullet_list(["Diff shows runbook updated in same PR as behavior change"]),
            "verify": bullet_list(["Checklist audit in CI optional"]),
            "obs": "MTTR improvements.",
            "doc": "Runbook style guide.",
        },
    ),
]

TESTS = [
    ("test-01-integration-per-service", "OSV-TEST-01 — Integration tests per service boundary", "§12", "Each service: contract tests against neighbors using test doubles where needed."),
    ("test-02-e2e-full-stack", "OSV-TEST-02 — E2E full-stack reference programs", "§12", "UI+API+DB+tests+deploy smoke on reference app per action-plan §8."),
    ("test-03-replay-golden", "OSV-TEST-03 — Replay tests on golden manifests", "§12", "Durable store replay matches expected projections."),
    ("test-04-chaos", "OSV-TEST-04 — Chaos tests", "§12", "Fault injection for scheduler, store, worker with expected containment."),
    ("test-05-security-promotion", "OSV-TEST-05 — Security + promotion tests", "§12", "Authz bypass, token replay, lease escape; lifecycle invalid transitions rejected."),
]

GOV = [
    (
        "gov-01-adrs",
        "OSV-GOV-01 — ADRs for major decisions",
        {
            "tier": "2.2",
            "section": "§13",
            "goal": "ADRs exist for each major contract/service choice with status.",
            "prereq": NONE,
            "in_scope": "`docs/adrs/` hygiene, template, index.",
            "out": "Auto-generated ADRs from commits.",
            "deliv": bullet_list(["ADR index", "Template"]),
            "done": bullet_list(["No merge without ADR when policy says required"]),
            "verify": bullet_list(["CI or bot checks ADR presence"]),
            "obs": "N/A",
            "doc": "ADR how-to.",
        },
    ),
    (
        "gov-02-threat-models",
        "OSV-GOV-02 — Threat models per trust boundary",
        {
            "tier": "2.2",
            "section": "§13",
            "goal": "Threat models updated when trust boundaries ship or move.",
            "prereq": "OSV-GOV-01.",
            "in_scope": "`docs/threat-models/` map to services.",
            "out": "Formal pen-test as code.",
            "deliv": bullet_list(["One threat model per major boundary"]),
            "done": bullet_list(["Review date < 6 months at release"]),
            "verify": bullet_list(["Security review sign-off linked"]),
            "obs": "Open findings count.",
            "doc": "Threat modeling process.",
        },
    ),
    (
        "gov-03-incident-forensics",
        "OSV-GOV-03 — Incident forensics tool operational",
        {
            "tier": "2.2",
            "section": "§13",
            "goal": "`tools/incident-forensics` works against real telemetry/traces.",
            "prereq": "OSV-SVC-observability-gateway; OSV-SVC-incident-ops.",
            "in_scope": "CLI, query packs, export for RCA.",
            "out": "Auto-remediation bots.",
            "deliv": bullet_list(["Tool README", "Sample investigation notebook"]),
            "done": bullet_list(["SRE drill completes using tool < SLA"]),
            "verify": bullet_list(["Fixture investigation reproduces known incident"]),
            "obs": "Tool usage.",
            "doc": "Forensics playbook.",
        },
    ),
]

READY = [
    (
        "ready-01-readiness-program",
        "OSV-READY-01 — Readiness / KPI program implemented",
        {
            "tier": "2.2",
            "section": "§14",
            "goal": "Readiness program + KPI dashboards from master architecture fed by observability-gateway — not placeholders.",
            "prereq": "OSV-SVC-observability-gateway; metric definitions.",
            "in_scope": "Dashboard JSON, owners, on-call linkage.",
            "out": "Executive narrative auto-slides.",
            "deliv": bullet_list(["Dashboard pack", "SLO definitions"]),
            "done": bullet_list(["On-call acknowledges alerts in drill"]),
            "verify": bullet_list(["Synthetic alert test"]),
            "obs": "Alert noise ratio.",
            "doc": "Readiness definitions.",
        },
    ),
    (
        "ready-02-core-metrics-scheduled",
        "OSV-READY-02 — Core growth & stability metrics on a schedule",
        {
            "tier": "2.2",
            "section": "§14",
            "goal": "Capability growth, error reduction, transfer, stability metrics computed on schedule with retention.",
            "prereq": "OSV-READY-01; OSV-SVC-evaluation.",
            "in_scope": "Jobs, storage, API for reading trends.",
            "out": "ML forecasting of incidents.",
            "deliv": bullet_list(["Job definitions", "Historical tables"]),
            "done": bullet_list(["90d history queryable"]),
            "verify": bullet_list(["Data quality tests"]),
            "obs": "Job failures.",
            "doc": "Metric dictionary.",
        },
    ),
]

EXTRACT = [
    (
        "extract-01-microservice-extraction",
        "OSV-EXTRACT-01 — Microservice extraction contract drills",
        {
            "tier": "2.2",
            "section": "§15",
            "goal": "Every service passes extraction drill: copy folder + contracts + SDKs only; register peers; conformance green.",
            "prereq": "All OSV-SVC-* complete for in-scope services.",
            "in_scope": "Automated drill script, CI matrix.",
            "out": "Kubernetes operator per service.",
            "deliv": bullet_list(["Drill script", "CI job"]),
            "done": bullet_list(["N services pass in CI"]),
            "verify": bullet_list(["Random service sampled quarterly"]),
            "obs": "Drill duration.",
            "doc": "Extraction README per service.",
        },
    ),
    (
        "extract-02-multitenant-boundaries",
        "OSV-EXTRACT-02 — Multi-tenant / org boundaries",
        {
            "tier": "2.2",
            "section": "§15",
            "goal": "Tenant/org isolation for IAM, quotas, data where applicable.",
            "prereq": "OSV-SVC-identity-authz; OSV-SVC-quota-scheduler.",
            "in_scope": "Tenant id propagation, isolation tests.",
            "out": "Cell-based multi-region tenancy.",
            "deliv": bullet_list(["Tenant context middleware", "Isolation tests"]),
            "done": bullet_list(["Cross-tenant data leak tests pass"]),
            "verify": bullet_list(["Fuzz tenant id confusion"]),
            "obs": "Isolation violations = 0.",
            "doc": "Tenancy ADR.",
        },
    ),
]


def svc_plan(name: str, idx: int) -> tuple[str, str, dict]:
    slug = f"svc-{name.replace('_', '-')}"
    vid = f"OSV-SVC-{idx:02d}-{name}"
    title = f"{vid} — Service `{name}`"
    special = ""
    if name == "lifecycle-governance":
        special = "Sole owner of promotion/autonomy mutations."
    elif name == "identity-authz":
        special = "Sole issuer/validator of scoped approval tokens."
    elif name == "policy-management":
        special = "Sole activator of policy bundles."
    elif name == "memory-lifecycle":
        special = "Sole memory mutator."
    elif name == "safety-controller":
        special = "Sole final veto on high-risk actions."
    goal = f"Deploy `{name}` with api/runtime/tests/README, contract conformance, extraction-ready layout. {special}".strip()
    return (
        slug,
        title,
        {
            "tier": "2.2",
            "section": f"§4 ({name})",
            "goal": goal,
            "prereq": "OSV-CONTRACTS-01 + relevant contract families published; OSV-ORCH-01 for RPC callers.",
            "in_scope": f"Service `{name}` behavior per master architecture + operating-system-folder-structure.",
            "out": "Features owned by other services without RPC delegation.",
            "deliv": bullet_list(
                [
                    "`api/` stable import surface",
                    "`runtime/` process + config",
                    "`tests/` unit+integration",
                    "Service README with deploy + extract steps",
                    "Observability hooks (metrics/logs/traces)",
                ]
            ),
            "done": bullet_list(
                [
                    "Contract conformance suite green",
                    "Service passes OSV-EXTRACT-01 drill",
                    "SLOs defined (even if initial)",
                ]
            ),
            "verify": bullet_list(
                [
                    "CI job id documented",
                    "Load smoke optional for applicable services",
                ]
            ),
            "obs": f"`{name}` health + SLO dashboards.",
            "doc": f"Service README + ADR links.",
        },
    )


def emit(slug: str, title: str, d: dict) -> None:
    body = plan(
        vid=title.split("—")[0].strip(),
        slug=slug,
        title=title,
        tier=d["tier"],
        section_ref=d["section"],
        goal=d["goal"],
        prerequisites=d["prereq"],
        in_scope=d["in_scope"],
        out_scope=d["out"],
        deliverables=d["deliv"],
        completion=d["done"],
        verification=d["verify"],
        observability=d["obs"],
        documentation=d["doc"],
    )
    path = PLANS / f"{slug}.md"
    path.write_text(body, encoding="utf-8")


def write_plan_index() -> int:
    paths = sorted(PLANS.glob("*.md"))
    index_lines = [
        "# Version plans index",
        "",
        "Auto-generated by `_generate_plans.py`. Regenerate after editing the generator or adding checklist-backed versions.",
        "",
        "| Plan | Title |",
        "|------|-------|",
    ]
    for p in paths:
        first = p.read_text(encoding="utf-8").splitlines()[0].removeprefix("# ").strip()
        index_lines.append(f"| [`{p.name}`](./plans/{p.name}) | {first} |")
    index_lines.extend(
        [
            "",
            "## In-repo milestone pointers",
            "",
            "- **OSV-STORY-01 (S1a / M2):** completion bar and **B1–B5** (closed in-repo) — [`../architecture/company-os-path-to-100-percent.md`](../architecture/company-os-path-to-100-percent.md) §3–§4.",
            "- **OSV-STORY-01 plan + evidence:** [`plans/story-01-stage1-intake.md`](./plans/story-01-stage1-intake.md) (edit in place after generation; see plan footer).",
            "",
        ]
    )
    (ROOT / "INDEX.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    return len(paths)


def emit_all_plans() -> None:
    PLANS.mkdir(parents=True, exist_ok=True)
    for slug, title, d in STORY:
        emit(slug, title, d)
    for slug, title, d in LADDER:
        emit(slug, title, d)
    for slug, title, d in CONTRACTS:
        emit(slug, title, d)
    for i, name in enumerate(SERVICES, start=1):
        emit(*svc_plan(name, i))
    for slug, title, d in ORCH:
        emit(slug, title, d)
    for slug, title, d in WORKER:
        emit(slug, title, d)
    for slug, title, d in AGENTS:
        emit(slug, title, d)
    for slug, title, goal in LIBS:
        emit(
            slug,
            title,
            {
                "tier": "2.2",
                "section": "§8 (libraries)",
                "goal": goal,
                "prereq": "OSV-CONTRACTS-01.",
                "in_scope": "Library package + tests + semver releases.",
                "out": "Alternate language ports.",
                "deliv": bullet_list(["Package on internal registry or path", "Usage examples", "CHANGELOG"]),
                "done": bullet_list(["At least one production service depends via pinned version"]),
                "verify": bullet_list(["Unit + integration consumer test"]),
                "obs": "Library error rates in consumers.",
                "doc": "Library README + migration notes.",
            },
        )
    for slug, title, d in DATA:
        emit(slug, title, d)
    for slug, title, d in INFRA:
        emit(slug, title, d)
    for slug, title, d in PRODUCT:
        emit(slug, title, d)
    for slug, title, sec, goal in TESTS:
        emit(
            slug,
            title,
            {
                "tier": "2.2",
                "section": sec,
                "goal": goal,
                "prereq": "Targets under test must exist.",
                "in_scope": "Test harness + CI wiring + flake policy.",
                "out": "Exhaustive formal verification of all code paths.",
                "deliv": bullet_list(["Test directory", "CI job", "Flake quarantine policy"]),
                "done": bullet_list(["CI green on main for 14 consecutive days or agreed bar"]),
                "verify": bullet_list(["Mutation / chaos / security as applicable"]),
                "obs": "Test duration, flake rate.",
                "doc": "Testing strategy ADR.",
            },
        )
    for slug, title, d in GOV:
        emit(slug, title, d)
    for slug, title, d in READY:
        emit(slug, title, d)
    for slug, title, d in EXTRACT:
        emit(slug, title, d)


def main(argv: list[str] | None = None) -> None:
    args = argv if argv is not None else sys.argv[1:]
    index_only = "--index-only" in args
    if index_only:
        if not PLANS.is_dir() or not any(PLANS.glob("*.md")):
            print("error: docs/versioning/plans/ is missing or empty; run full generator first", file=sys.stderr)
            raise SystemExit(2)
    else:
        emit_all_plans()
    n = write_plan_index()
    if index_only:
        print(f"Wrote INDEX.md only (--index-only); indexed {n} plans under {PLANS}")
    else:
        print(f"Wrote {n} plans under {PLANS} and INDEX.md")


if __name__ == "__main__":
    main()
