"""Stage 1 (V2) intake file stubs under a project session directory (OSV-STORY-01 helper)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from sde_foundations.storage import ensure_dir, write_json
from sde_gates.time_util import iso_now

_INTAKE_EXCERPT_MAX = 800


def _goal_excerpt(goal: str) -> str:
    g = (goal or "").strip()
    if len(g) <= _INTAKE_EXCERPT_MAX:
        return g
    return g[:_INTAKE_EXCERPT_MAX] + "…"


def scaffold_project_intake(
    session_dir: Path,
    *,
    goal: str,
    repo_label: str = "unknown",
) -> dict[str, Any]:
    """
    Write ``intake/`` artifacts next to ``project_plan.json`` (does **not** create or edit the plan).

    Returns a summary dict with ``written`` paths (relative to ``session_dir``) and ``session_dir``.
    """
    session_dir = session_dir.resolve()
    if not session_dir.is_dir():
        return {"ok": False, "error": "session_dir_not_a_directory", "session_dir": str(session_dir)}
    excerpt = _goal_excerpt(goal)
    if not excerpt:
        return {"ok": False, "error": "goal_empty", "session_dir": str(session_dir)}

    intake = session_dir / "intake"
    ensure_dir(intake)
    written: list[str] = []

    disc: dict[str, Any] = {
        "schema_version": "1.0",
        "repo_id": str(repo_label).strip() or "unknown",
        "source": "project_intake_scaffold",
        "goal_excerpt": excerpt,
        "constraints": [],
        "non_goals": [],
        "open_questions": [],
        "created_at": iso_now(),
    }
    write_json(intake / "discovery.json", disc)
    written.append("intake/discovery.json")
    write_json(
        intake / "planner_identity.json",
        {
            "schema_version": "1.0",
            "actor_id": "planner_scaffold_stub",
            "role": "planner",
            "created_at": iso_now(),
        },
    )
    written.append("intake/planner_identity.json")

    digest = "\n".join(
        [
            "# Research digest (session intake scaffold)",
            "",
            f"- **Session:** `{session_dir.name}`",
            f"- **Repo label:** `{repo_label}`",
            "",
            "## Goal excerpt",
            "",
            "```text",
            excerpt,
            "```",
            "",
            "## Notes",
            "",
            "- Generated by `sde project scaffold-intake`. Replace with planner output when wired.",
            "",
        ]
    )
    (intake / "research_digest.md").write_text(digest, encoding="utf-8")
    written.append("intake/research_digest.md")

    write_json(
        intake / "doc_review.json",
        {
            "schema_version": "1.0",
            "passed": True,
            "reviewed_at": iso_now(),
            "findings": [],
            "reviewer": "intake_scaffold_stub",
            "note": "Replace with separate reviewer agent output before treating as evidence.",
        },
    )
    written.append("intake/doc_review.json")
    write_json(
        intake / "reviewer_identity.json",
        {
            "schema_version": "1.0",
            "actor_id": "intake_scaffold_stub",
            "role": "reviewer",
            "reviewed_at": iso_now(),
            "attestation_type": "local_stub",
            "attestation": "replace_with_real_reviewer_identity_proof",
        },
    )
    written.append("intake/reviewer_identity.json")

    q_lines = [{"id": "scaffold-1", "status": "resolved", "topic": "intake_scaffold"}]
    (intake / "question_workbook.jsonl").write_text(
        "\n".join(json.dumps(q) for q in q_lines) + "\n",
        encoding="utf-8",
    )
    written.append("intake/question_workbook.jsonl")

    (intake / "README.txt").write_text(
        "\n".join(
            [
                "Stage 1 intake stubs (OSV-STORY-01 helper).",
                "discovery.json, doc_review.json, research_digest.md, and question_workbook.jsonl (tail) are merged into each step context_pack when present.",
                "Keep project_plan.json as the driver contract.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    written.append("intake/README.txt")

    return {
        "ok": True,
        "session_dir": str(session_dir),
        "written": written,
    }
