#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "versions" / "2026-04-22-scale-feature-audit"


FEATURES = [
    {
        "feature": "Local-first non-regression gate (everyday use)",
        "score_a": 28,
        "score_b": 28,
        "confirmed_score": 28,
        "agent_a_missing": [
            "Add explicit non-regression gate comparing pre/post local UX latency and reliability.",
            "Enforce startup-time budget in automated tests.",
            "Add cold-start and warm-start benchmark suite for local mode.",
            "Add local workflow golden tests for all core commands.",
            "Fail CI when local usability SLOs regress.",
            "Track local developer-facing error rate over time.",
            "Add local resource ceiling tests under load.",
            "Add release gate that blocks on local regression findings.",
        ],
        "agent_b_missing": [
            "Add mandatory pre-merge gate for local startup/runtime regression thresholds.",
            "Run automated local CLI smoke suite in CI for every scale-related change.",
            "Define local reliability SLOs (success rate, p95 runtime, recovery).",
            "Track historical local baseline metrics and compare per PR.",
            "Add explicit regression tests for daily local workflows.",
            "Block release if contract checks pass but local UX workflows fail.",
            "Link scale feature flags to local non-regression checks.",
            "Publish one executable gate command for CI and local preflight.",
        ],
        "confirmed_missing": [
            "Implement enforceable local non-regression policy.",
            "Add latency and reliability baseline tracking for local workflows.",
            "Cover startup and daily workflow regressions in CI.",
            "Make local SLO breaches a hard release blocker.",
            "Create deterministic local perf benchmark suite.",
            "Add resource limit regression tests for local mode.",
            "Unify preflight and CI gating command.",
            "Persist trend history for local quality signals.",
        ],
    },
    {
        "feature": "Local and server semantic parity enforcement",
        "score_a": 8,
        "score_b": 12,
        "confirmed_score": 8,
        "agent_a_missing": [
            "Define canonical local-vs-server parity matrix per API/tool operation.",
            "Implement shared conformance harness against both runtimes.",
            "Add idempotency parity assertions across adapters.",
            "Add authz-decision parity assertions.",
            "Add state-transition parity assertions.",
            "Add retriable/non-retriable error taxonomy parity assertions.",
            "Persist parity results as versioned artifacts.",
            "Gate CI and deployment on parity drift.",
        ],
        "agent_b_missing": [
            "Implement server runtime path that uses local contract validators.",
            "Create golden local-vs-server semantic parity test suite.",
            "Add idempotency replay parity tests.",
            "Add authz decision replay parity tests.",
            "Enforce state transition parity matrices in CI.",
            "Add parity diff tooling for API responses and error codes.",
            "Block deploy on semantic parity drift.",
            "Publish shared semantic contract package for both runtimes.",
        ],
        "confirmed_missing": [
            "Build executable local-vs-server parity harness.",
            "Validate authz/idempotency/state transitions for both environments.",
            "Detect and report semantic response drift automatically.",
            "Gate release on parity failures.",
            "Persist parity audit artifacts per run.",
            "Share one contract package across runtime adapters.",
            "Run parity checks continuously in CI.",
            "Add remediation playbook for parity failures.",
        ],
    },
    {
        "feature": "Control plane / data plane split",
        "score_a": 12,
        "score_b": 18,
        "confirmed_score": 12,
        "agent_a_missing": [
            "Create separate deployable control-plane service.",
            "Create separate deployable data-plane worker service.",
            "Define network/API contract between planes.",
            "Implement independent scaling policies per plane.",
            "Implement plane-specific authn/authz boundaries.",
            "Add fault-isolation tests across plane failures.",
            "Add observability dimensions partitioned by plane.",
            "Add rollout and rollback procedures per plane.",
        ],
        "agent_b_missing": [
            "Create deploy topology that routes traffic to separate planes.",
            "Enforce control->data API contracts over network boundary.",
            "Add independent autoscaling knobs per plane.",
            "Add failure isolation tests for plane outages.",
            "Add auth boundary between planes.",
            "Add separate telemetry pipelines and dashboards.",
            "Add runtime routing that prevents plane coupling.",
            "Document operational ownership split by plane.",
        ],
        "confirmed_missing": [
            "Implement true deploy-time control/data plane split.",
            "Enforce plane boundary API contract.",
            "Separate scaling and ownership for both planes.",
            "Isolate failures between control and data paths.",
            "Apply dedicated security policies between planes.",
            "Split telemetry dashboards by plane.",
            "Add rollout/rollback process for each plane.",
            "Prove split behavior with integration tests.",
        ],
    },
    {
        "feature": "Async job plane for long-running API operations",
        "score_a": 18,
        "score_b": 16,
        "confirmed_score": 16,
        "agent_a_missing": [
            "Implement durable job queue backend.",
            "Implement job lifecycle API (submit/get/cancel/retry).",
            "Persist job state across process restarts.",
            "Implement worker heartbeat and lease renewal.",
            "Add dead-letter queue for poison jobs.",
            "Add bounded backoff policy with jitter.",
            "Expose async status endpoint with progress semantics.",
            "Add e2e tests for long-running queue-backed operations.",
        ],
        "agent_b_missing": [
            "Add API async handoff (`202 + job_id`) for long operations.",
            "Implement decoupled worker processes.",
            "Add job status states (`queued/running/succeeded/failed/cancelled`).",
            "Persist retry/backoff state across restarts.",
            "Add dead-letter queue replay tooling.",
            "Define delivery guarantees with tests.",
            "Add queue lag metrics and SLO alerts.",
            "Add cancellation and timeout semantics per job class.",
        ],
        "confirmed_missing": [
            "Stand up durable queue-backed async execution plane.",
            "Expose complete job lifecycle API.",
            "Persist and recover job state on restarts.",
            "Add DLQ and replay operations.",
            "Implement safe retry budgets and jittered backoff.",
            "Publish queue health metrics and alerts.",
            "Support deterministic cancel/timeout behavior.",
            "Cover async flow end-to-end with tests.",
        ],
    },
    {
        "feature": "Edge admission control (rate limits + Retry-After)",
        "score_a": 2,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Implement edge gateway middleware for admission control.",
            "Implement per-route and global rate limits.",
            "Emit standards-compliant `Retry-After` headers.",
            "Add tenant-aware rate-limit keys.",
            "Add burst and sustained traffic controls.",
            "Add throttle/deny observability counters.",
            "Add integration tests for 429 response semantics.",
            "Add dynamic policy update support.",
        ],
        "agent_b_missing": [
            "Implement request rate limiter at edge boundary.",
            "Emit deterministic 429 responses.",
            "Emit deterministic `Retry-After` values.",
            "Add user/tenant/API-key scoped buckets.",
            "Add burst+sustained limit config.",
            "Add limiter rejection metrics.",
            "Add limiter outage fail-open/fail-closed policy.",
            "Add load tests validating edge backpressure.",
        ],
        "confirmed_missing": [
            "Build real edge admission controller.",
            "Implement standards-compliant 429 + `Retry-After` responses.",
            "Enforce scoped tenant/user/API-key limits.",
            "Support burst and sustained budgets.",
            "Expose limiter metrics and alerts.",
            "Define limiter outage behavior.",
            "Exercise admission behavior in integration/load tests.",
            "Make policy updates runtime-safe.",
        ],
    },
    {
        "feature": "Per-tenant quotas and concurrency budgets",
        "score_a": 16,
        "score_b": 10,
        "confirmed_score": 10,
        "agent_a_missing": [
            "Implement tenant identity propagation through runtime.",
            "Implement durable per-tenant quota state storage.",
            "Enforce per-tenant concurrency ceilings in scheduler.",
            "Implement fairness policy across tenants.",
            "Implement quota reset windows and rollover rules.",
            "Expose quota usage APIs.",
            "Add over-quota rejection reasons.",
            "Add multi-tenant stress tests for fairness.",
        ],
        "agent_b_missing": [
            "Introduce tenant identity throughout scheduling path.",
            "Implement per-tenant concurrency counters.",
            "Implement quota refill logic.",
            "Add hard-stop behavior when budgets are exhausted.",
            "Add tenant-level observability for budget usage.",
            "Add multi-tenant integration tests.",
            "Add admin APIs to configure quotas.",
            "Add tenant fairness validation under contention.",
        ],
        "confirmed_missing": [
            "Thread tenant identity through scheduling and execution.",
            "Persist per-tenant quota and concurrency state.",
            "Enforce hard limits with clear rejection reasons.",
            "Implement fairness policy for contention.",
            "Support quota refill window semantics.",
            "Publish tenant budget observability.",
            "Add multi-tenant stress/integration coverage.",
            "Provide admin controls for quota policies.",
        ],
    },
    {
        "feature": "Idempotent invocation and side-effect deduplication",
        "score_a": 10,
        "score_b": 24,
        "confirmed_score": 10,
        "agent_a_missing": [
            "Define canonical idempotency key format and scope.",
            "Persist idempotency ledger with TTL and collision protection.",
            "Enforce idempotency check at API entrypoint.",
            "Replay canonical prior responses for duplicate keys.",
            "Deduplicate downstream side effects across retries.",
            "Handle concurrent duplicate submissions safely.",
            "Add exactly-once side-effect tests.",
            "Add observability for dedupe hit/conflict outcomes.",
        ],
        "agent_b_missing": [
            "Extend idempotency from storage events to API invocation layer.",
            "Implement global dedupe ledger across services/plugins.",
            "Add idempotency TTL and replay windows.",
            "Add duplicate-but-different payload conflict contract.",
            "Add cross-process concurrency dedupe tests.",
            "Add outbox integration for external side effects.",
            "Add plugin/tool-call idempotency propagation.",
            "Add idempotency hit/miss/conflict metrics.",
        ],
        "confirmed_missing": [
            "Promote idempotency from storage-only to full invocation path.",
            "Implement global dedupe ledger across services/plugins.",
            "Enforce API-level key validation and replay semantics.",
            "Handle concurrent duplicate writes safely.",
            "Deduplicate external side effects via outbox pattern.",
            "Define and test conflict response semantics.",
            "Add TTL/replay policy for keys.",
            "Publish idempotency metrics and alerts.",
        ],
    },
    {
        "feature": "Distributed queue fairness (weighted scheduling)",
        "score_a": 6,
        "score_b": 6,
        "confirmed_score": 6,
        "agent_a_missing": [
            "Implement distributed queue abstraction.",
            "Add weighted fairness algorithm.",
            "Add tenant/plugin priority classes.",
            "Implement starvation prevention guarantees.",
            "Persist scheduler state for crash recovery.",
            "Add mixed-workload scheduling simulation tests.",
            "Expose wait-time and fairness metrics.",
            "Add safe admin controls for weight tuning.",
        ],
        "agent_b_missing": [
            "Implement worker-consumed distributed queue.",
            "Add weighted fair scheduling algorithm.",
            "Add per-tenant and per-plugin weight assignment.",
            "Add aging policy to avoid starvation.",
            "Add fairness metrics by class.",
            "Add load tests for noisy-neighbor control.",
            "Persist scheduling decisions across restarts.",
            "Add deterministic replay tests for scheduler output.",
        ],
        "confirmed_missing": [
            "Deliver distributed weighted fair queue.",
            "Support tenant and plugin priority weighting.",
            "Prevent starvation with aging policy.",
            "Persist scheduler state/replay behavior.",
            "Publish fairness and wait-time telemetry.",
            "Tune policies with safe admin controls.",
            "Validate behavior under mixed-load stress.",
            "Add deterministic scheduler tests.",
        ],
    },
    {
        "feature": "Per-plugin circuit breakers and retry budgets",
        "score_a": 4,
        "score_b": 2,
        "confirmed_score": 2,
        "agent_a_missing": [
            "Define plugin identity and health state model.",
            "Implement per-plugin circuit breaker state machine.",
            "Implement per-plugin retry budget tracking.",
            "Integrate breaker decisions into invocation path.",
            "Add cooldown and probe policies.",
            "Add bulkhead isolation for failing plugins.",
            "Add containment tests for cascading failures.",
            "Expose breaker telemetry and controls.",
        ],
        "agent_b_missing": [
            "Implement plugin-specific circuit breaker states.",
            "Implement plugin-specific retry budget accounting.",
            "Add open/half-open/closed transition metrics.",
            "Add fallback policy for open circuits.",
            "Add transient/permanent failure classification.",
            "Add breaker config API with safe defaults.",
            "Add synthetic plugin-failure integration tests.",
            "Alert on breaker-open saturation.",
        ],
        "confirmed_missing": [
            "Implement plugin-level circuit breaker runtime.",
            "Add plugin-level retry budget enforcement.",
            "Classify failures to drive breaker transitions.",
            "Add fallback behavior for open circuits.",
            "Contain plugin failure blast radius via bulkheads.",
            "Expose state transitions in telemetry.",
            "Provide operator-safe breaker controls.",
            "Test degraded plugin scenarios end-to-end.",
        ],
    },
    {
        "feature": "MCP broker/session lifecycle management",
        "score_a": 3,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Implement MCP broker service for routing and mediation.",
            "Define broker session state machine.",
            "Implement session lease/heartbeat handling.",
            "Implement reconnect/resume semantics.",
            "Implement broker-side authn/authz.",
            "Persist broker session metadata.",
            "Add broker load and failover tests.",
            "Add broker session telemetry.",
        ],
        "agent_b_missing": [
            "Implement broker abstraction for MCP sessions.",
            "Implement create/resume/terminate lifecycle APIs.",
            "Persist session state with expiry semantics.",
            "Add stale-session reclamation.",
            "Add broker routing to plugin runtimes.",
            "Add disconnect/reconnect integration tests.",
            "Add broker latency/failure metrics.",
            "Add broker policy enforcement checks.",
        ],
        "confirmed_missing": [
            "Build MCP broker service.",
            "Define full MCP session lifecycle API.",
            "Persist and reclaim sessions safely.",
            "Support heartbeat and resume behavior.",
            "Enforce authz at broker boundary.",
            "Route sessions to plugin runtime deterministically.",
            "Add failover/disconnect integration tests.",
            "Ship broker observability and alerts.",
        ],
    },
    {
        "feature": "Plugin discovery/registry compatibility governance",
        "score_a": 5,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Implement plugin registry service.",
            "Define metadata/version contract schema.",
            "Implement compatibility matrix evaluation.",
            "Implement canary compatibility checks.",
            "Enforce publish-time validation gates.",
            "Add deprecation and rollback-safe version policies.",
            "Add signed metadata verification.",
            "Add governance reports and audit history.",
        ],
        "agent_b_missing": [
            "Implement registry data model and storage.",
            "Implement plugin discovery APIs.",
            "Implement semantic version compatibility rules.",
            "Run compatibility checks at publish time.",
            "Validate canary compatibility before broad rollout.",
            "Enforce deprecation windows.",
            "Verify plugin provenance/signatures.",
            "Add incompatible plugin rejection tests.",
        ],
        "confirmed_missing": [
            "Stand up real plugin registry service.",
            "Enforce plugin metadata and version contracts.",
            "Automate compatibility matrix checks.",
            "Gate publish and rollout with compatibility validation.",
            "Add deprecation and rollback-safe governance.",
            "Verify plugin provenance and signatures.",
            "Persist governance audit history.",
            "Test incompatible version rejection paths.",
        ],
    },
    {
        "feature": "Plugin/runtime bulkheads by trust class",
        "score_a": 4,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Define trust classes and execution policies.",
            "Implement isolated worker pools per trust class.",
            "Route plugin execution by trust class.",
            "Enforce resource quotas per trust class.",
            "Prevent cross-class state leakage.",
            "Implement cross-class communication guardrails.",
            "Add trust-boundary penetration tests.",
            "Add trust-class segmented metrics.",
        ],
        "agent_b_missing": [
            "Define trust-class mapping policy.",
            "Create isolated runtime pools by trust class.",
            "Enforce trust-class routing at dispatch time.",
            "Apply class-level resource limits.",
            "Prevent cross-class sharing.",
            "Add escalation path for misclassification.",
            "Add blast-radius containment chaos tests.",
            "Add trust-class audit logs.",
        ],
        "confirmed_missing": [
            "Define and enforce trust classes for plugin runtime.",
            "Segment execution pools by trust class.",
            "Apply strict class-level quotas and isolation.",
            "Block cross-class state/resource leakage.",
            "Add trust boundary policy and audit controls.",
            "Test trust boundary containment under failure.",
            "Handle plugin trust reclassification safely.",
            "Expose trust-class telemetry for operations.",
        ],
    },
    {
        "feature": "Sandbox hardening (egress allowlists, cgroups, limits)",
        "score_a": 7,
        "score_b": 1,
        "confirmed_score": 1,
        "agent_a_missing": [
            "Implement container/OS sandbox isolation.",
            "Enforce network egress allowlist.",
            "Enforce CPU/memory/pid/fd limits.",
            "Enforce filesystem mount and write restrictions.",
            "Add syscall/profile restrictions.",
            "Implement sandbox escape detection and kill-switch.",
            "Add hardening tests for exhaustion and egress bypass.",
            "Version and validate sandbox policies.",
        ],
        "agent_b_missing": [
            "Implement egress allowlist enforcement.",
            "Implement cgroup limits for CPU/memory/pids.",
            "Implement filesystem isolation policies.",
            "Implement syscall filtering.",
            "Implement per-execution timeout and kill semantics.",
            "Validate sandbox policy configs at startup.",
            "Add adversarial sandbox escape tests.",
            "Add sandbox deny audit logs.",
        ],
        "confirmed_missing": [
            "Deliver production sandbox isolation runtime.",
            "Block outbound traffic by default using allowlists.",
            "Apply cgroup/resource limits per invocation.",
            "Restrict filesystem and syscall surface.",
            "Enforce timeouts and hard kill behavior.",
            "Log all denied sandbox operations.",
            "Test escape and exhaustion adversarial paths.",
            "Version and validate sandbox policies.",
        ],
    },
    {
        "feature": "Local vs production semantic parity gates",
        "score_a": 9,
        "score_b": 10,
        "confirmed_score": 9,
        "agent_a_missing": [
            "Define production-equivalent parity harness.",
            "Implement parity gate executor for both environments.",
            "Add artifact-level semantic diffing.",
            "Add state/check/error semantic comparators.",
            "Store gate results as immutable artifacts.",
            "Fail release on parity drift.",
            "Add failure remediation hints.",
            "Run scheduled parity regression jobs.",
        ],
        "agent_b_missing": [
            "Define executable parity gate contract.",
            "Add production-like environment runner.",
            "Add endpoint-level semantic parity checks.",
            "Add authz parity checks.",
            "Add idempotency/retry parity checks.",
            "Publish parity gate result artifact.",
            "Block release pipeline on parity failure.",
            "Add debugging output for parity drift.",
        ],
        "confirmed_missing": [
            "Define executable local/prod parity gate contract.",
            "Run parity checks against both environments.",
            "Compare semantic outputs, transitions, and errors.",
            "Include authz and idempotency parity assertions.",
            "Persist immutable parity results.",
            "Fail release on drift.",
            "Provide diagnostic outputs for drift triage.",
            "Schedule continuous parity regression runs.",
        ],
    },
    {
        "feature": "Local/prod config overlay with invariant semantics",
        "score_a": 11,
        "score_b": 14,
        "confirmed_score": 11,
        "agent_a_missing": [
            "Create unified config schema for local and prod.",
            "Implement startup fail-fast validation for adapters.",
            "Mark invariant fields and enforce semantics.",
            "Implement deterministic overlay precedence.",
            "Add config drift detector.",
            "Add redaction and secret-source validation.",
            "Add backward-compatible config migration tooling.",
            "Add integration tests for overlay behavior.",
        ],
        "agent_b_missing": [
            "Implement shared config schema consumed by both runtimes.",
            "Implement overlay merge logic.",
            "Declare invariant fields across overlays.",
            "Fail startup on invariant violations.",
            "Add env-specific override allowlist.",
            "Add secret handling rules.",
            "Add CI tests comparing local/prod config resolutions.",
            "Add versioned config migration tooling.",
        ],
        "confirmed_missing": [
            "Introduce one schema for local/prod config.",
            "Implement deterministic overlay merge engine.",
            "Enforce invariants with startup fail-fast checks.",
            "Detect and report config drift.",
            "Constrain environment overrides safely.",
            "Handle secrets/redaction consistently.",
            "Support versioned config migrations.",
            "Test config overlays across all runtime adapters.",
        ],
    },
    {
        "feature": "Contract-version negotiation for MCP/plugins",
        "score_a": 2,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Define MCP/plugin version negotiation handshake.",
            "Implement supported-version advertisement.",
            "Implement compatibility fallback strategy.",
            "Implement hard rejection for unsafe incompatible versions.",
            "Implement deprecation windows.",
            "Add negotiation outcome telemetry.",
            "Add dual-version serving for rollback safety.",
            "Add mixed-version integration tests.",
        ],
        "agent_b_missing": [
            "Define protocol negotiation handshake.",
            "Advertise supported version ranges.",
            "Implement client-side downgrade selection.",
            "Hard-fail on incompatible intersections.",
            "Add compatibility matrix tests.",
            "Add rollback-safe staged negotiation behavior.",
            "Emit negotiated version/failure telemetry.",
            "Enforce runtime deprecation windows.",
        ],
        "confirmed_missing": [
            "Implement MCP/plugin contract version negotiation.",
            "Advertise and select compatible version ranges.",
            "Reject unsafe incompatible versions deterministically.",
            "Support rollback-safe dual-version behavior.",
            "Enforce and test deprecation windows.",
            "Track negotiated versions in telemetry.",
            "Exercise mixed-version fleet scenarios.",
            "Gate rollout on compatibility failures.",
        ],
    },
    {
        "feature": "Plugin authz scopes and least-privilege policy engine",
        "score_a": 9,
        "score_b": 8,
        "confirmed_score": 8,
        "agent_a_missing": [
            "Define plugin-specific scope taxonomy.",
            "Implement scope policy evaluation engine.",
            "Bind scope checks to each plugin/tool invocation.",
            "Implement deny-by-default behavior.",
            "Add policy authoring/versioning workflow.",
            "Add policy simulation tool.",
            "Add audit logs for allow/deny decisions.",
            "Add privilege-escalation tests.",
        ],
        "agent_b_missing": [
            "Define plugin scope permission model.",
            "Implement policy evaluator for plugin scopes.",
            "Bind scopes to plugin identity at invocation.",
            "Implement deny-by-default for unspecified scopes.",
            "Implement scope inheritance constraints.",
            "Log every scope decision.",
            "Add escalation attempt tests.",
            "Add admin APIs for plugin scope policy management.",
        ],
        "confirmed_missing": [
            "Create plugin scope taxonomy and permission model.",
            "Implement least-privilege scope policy engine.",
            "Enforce scope checks on every plugin invocation.",
            "Default deny when scope is undefined.",
            "Add versioned policy authoring/simulation.",
            "Log and audit allow/deny decisions.",
            "Test privilege escalation and scope confusion paths.",
            "Provide admin policy controls.",
        ],
    },
    {
        "feature": "Cross-tenant isolation for plugin/tool execution",
        "score_a": 6,
        "score_b": 6,
        "confirmed_score": 6,
        "agent_a_missing": [
            "Introduce tenant identity in execution context.",
            "Create tenant-isolated execution sandboxes.",
            "Isolate queue/state/storage by tenant.",
            "Block cross-tenant cache/artifact reuse.",
            "Add tenant-scoped encryption keys.",
            "Add isolation runtime assertions.",
            "Add adversarial cross-tenant tests.",
            "Add tenant incident containment procedures.",
        ],
        "agent_b_missing": [
            "Thread tenant identity through plugin/tool execution pipeline.",
            "Isolate execution state and caches per tenant.",
            "Isolate queues and worker pools by tenant class.",
            "Enforce tenant data boundaries at storage layer.",
            "Add cross-tenant leakage tests.",
            "Add tenant-aware compute budget enforcement.",
            "Add tenant-specific key-management boundaries.",
            "Add tenant isolation audit signals.",
        ],
        "confirmed_missing": [
            "Carry tenant identity across the full execution path.",
            "Isolate runtime state, queues, and storage by tenant.",
            "Prevent cross-tenant cache/artifact reuse.",
            "Apply tenant-specific keys and policy controls.",
            "Enforce tenant budgets and guardrails.",
            "Continuously audit for isolation boundary violations.",
            "Add adversarial leakage tests.",
            "Define containment actions for tenant isolation incidents.",
        ],
    },
    {
        "feature": "End-to-end plugin observability (API->MCP->runtime)",
        "score_a": 10,
        "score_b": 10,
        "confirmed_score": 10,
        "agent_a_missing": [
            "Add plugin invocation spans with stable plugin IDs.",
            "Propagate correlation IDs across API, MCP, runtime.",
            "Emit standardized plugin error taxonomy.",
            "Add per-plugin/per-tenant SLIs.",
            "Implement distributed trace stitching.",
            "Add plugin dashboards and alert rules.",
            "Store/query plugin call logs with retention.",
            "Add end-to-end synthetic observability tests.",
        ],
        "agent_b_missing": [
            "Implement correlation ID propagation from API to runtime.",
            "Emit structured events for each plugin call stage.",
            "Add MCP broker observability hooks.",
            "Add plugin latency/error/throughput SLIs.",
            "Add trace stitching across boundaries.",
            "Add plugin dashboards and alerts.",
            "Add trace sampling and retention policies.",
            "Add correlation continuity integration tests.",
        ],
        "confirmed_missing": [
            "Propagate correlation IDs API->MCP->plugin runtime.",
            "Emit stage-level plugin spans/events.",
            "Normalize plugin error/outcome taxonomy.",
            "Track plugin and tenant SLIs/SLOs.",
            "Stitch traces across service boundaries.",
            "Ship plugin-specific dashboards and alerts.",
            "Store logs/traces with retention policies.",
            "Validate observability continuity with tests.",
        ],
    },
    {
        "feature": "Per-plugin/per-tenant cost attribution and caps",
        "score_a": 5,
        "score_b": 0,
        "confirmed_score": 0,
        "agent_a_missing": [
            "Define cost model dimensions per plugin and tenant.",
            "Collect normalized usage units per invocation.",
            "Aggregate costs near real-time.",
            "Implement configurable hard/soft spend caps.",
            "Enforce deterministic deny on cap breach.",
            "Add forecast and burn-rate computations.",
            "Add billing/audit exports.",
            "Add cap race-condition tests.",
        ],
        "agent_b_missing": [
            "Implement per-plugin usage metering.",
            "Implement per-tenant usage metering.",
            "Define billable unit/pricing dimensions.",
            "Implement hard and soft budget caps.",
            "Enforce caps at admission layer in real time.",
            "Emit cost attribution reports/APIs.",
            "Add cost anomaly detection.",
            "Add cap breach and recovery tests.",
        ],
        "confirmed_missing": [
            "Implement per-plugin and per-tenant metering pipeline.",
            "Define normalized cost model and billable units.",
            "Aggregate usage into near-real-time attribution.",
            "Enforce hard/soft budget caps at admission.",
            "Provide cap breach response contracts.",
            "Generate cost reports and audit exports.",
            "Detect cost anomalies and burn-rate spikes.",
            "Test cap enforcement under concurrency.",
        ],
    },
    {
        "feature": "Artifact keying parity (local mirror vs object store)",
        "score_a": 12,
        "score_b": 12,
        "confirmed_score": 12,
        "agent_a_missing": [
            "Define canonical key schema shared across local/object store.",
            "Implement deterministic object-store writer.",
            "Implement local-object key reconciliation checks.",
            "Detect/report key collisions and drift.",
            "Add migration tooling for legacy key formats.",
            "Add checksum integrity verification across stores.",
            "Add retry-safe atomic upload semantics.",
            "Add parity integration tests across backends.",
        ],
        "agent_b_missing": [
            "Define canonical artifact key schema.",
            "Implement object-store adapter for canonical keys.",
            "Implement reconciliation job between local and object-store keys.",
            "Add content-hash integrity checks.",
            "Add migration path from legacy local keys.",
            "Add parity test suite across storage backends.",
            "Add conflict resolution policy for divergent artifacts.",
            "Add drift observability and alerts.",
        ],
        "confirmed_missing": [
            "Adopt one canonical artifact key schema.",
            "Implement canonical object-store read/write adapter.",
            "Reconcile local mirror keys vs object-store keys.",
            "Detect collisions and key drift automatically.",
            "Use checksums/content hashes for integrity.",
            "Support migration from legacy key layouts.",
            "Define conflict resolution semantics for drift.",
            "Validate parity with backend integration tests.",
        ],
    },
    {
        "feature": "Progressive rollout/canary/rollback for plugin versions",
        "score_a": 7,
        "score_b": 8,
        "confirmed_score": 7,
        "agent_a_missing": [
            "Implement plugin version traffic-splitting controller.",
            "Implement staged rollout policy.",
            "Define health gates for promotion.",
            "Implement auto rollback on SLO breach.",
            "Track rollout state/history per plugin.",
            "Support safe pause/resume controls.",
            "Add canary failure integration tests.",
            "Add operator override APIs.",
        ],
        "agent_b_missing": [
            "Implement plugin version routing by traffic percentage.",
            "Implement canary cohort assignment.",
            "Implement health gate checks tied to plugin versions.",
            "Implement automatic rollback trigger on SLO breach.",
            "Implement staged rollout progression controller.",
            "Persist rollout history for auditability.",
            "Add upgrade/canary/rollback lifecycle tests.",
            "Add operator pause/resume/force-rollback controls.",
        ],
        "confirmed_missing": [
            "Build plugin version progressive rollout controller.",
            "Support canary cohorts and staged traffic percentages.",
            "Enforce health-gated promotion logic.",
            "Auto-rollback on SLO or policy breach.",
            "Persist rollout timeline for auditability.",
            "Provide pause/resume/override operations.",
            "Test full canary and rollback lifecycle.",
            "Integrate rollout actions with observability signals.",
        ],
    },
    {
        "feature": "Scale failure drills (provider 429, queue lag, restart)",
        "score_a": 6,
        "score_b": 3,
        "confirmed_score": 3,
        "agent_a_missing": [
            "Implement deterministic failure-drill runner.",
            "Add provider 429 simulation scenarios.",
            "Add queue lag saturation scenarios.",
            "Add worker/broker restart fault scenarios.",
            "Define pass/fail SLO assertions for drills.",
            "Integrate drills into CI/nightly reliability suite.",
            "Persist drill reports with trend tracking.",
            "Validate automated remediation after drills.",
        ],
        "agent_b_missing": [
            "Implement automated failure drill framework.",
            "Add provider 429 simulation in integration environment.",
            "Add queue lag injection and detection tests.",
            "Add worker restart/crash recovery drills.",
            "Define pass/fail criteria per drill.",
            "Record drill outcomes as versioned artifacts.",
            "Schedule drills in CI/CD reliability jobs.",
            "Alert on drill regressions against baseline.",
        ],
        "confirmed_missing": [
            "Create executable reliability drill framework.",
            "Simulate provider 429 and queue lag failures.",
            "Simulate restart/crash recovery behavior.",
            "Define drill SLO-based pass/fail criteria.",
            "Persist and trend drill outcomes.",
            "Run drills automatically in CI/nightly jobs.",
            "Alert on drill quality regression.",
            "Verify remediation behavior under drills.",
        ],
    },
    {
        "feature": "Incident runbooks for plugin outage/saturation/auth",
        "score_a": 8,
        "score_b": 2,
        "confirmed_score": 2,
        "agent_a_missing": [
            "Write plugin outage runbook with containment steps.",
            "Write saturation runbook with throttling/shedding actions.",
            "Write auth failure runbook with diagnosis flow.",
            "Create machine-executable runbook checks.",
            "Add runbook ownership and escalation metadata.",
            "Link runbooks to alerts/dashboards.",
            "Add game-day validation tests.",
            "Version and review runbooks with change control.",
        ],
        "agent_b_missing": [
            "Create versioned runbook artifacts for plugin outage.",
            "Create runbook for plugin saturation/backpressure.",
            "Create runbook for plugin auth/authz incidents.",
            "Add executable checklist scripts referenced by runbooks.",
            "Add owner/on-call escalation metadata.",
            "Add runbook validation tests.",
            "Add runbook drill cadence and evidence capture.",
            "Add post-incident feedback loop into runbook updates.",
        ],
        "confirmed_missing": [
            "Author production incident runbooks for outage, saturation, and auth.",
            "Add executable steps/scripts for each runbook.",
            "Attach ownership and escalation metadata.",
            "Connect runbooks to alerts and dashboards.",
            "Version and review runbooks under change control.",
            "Validate runbooks with game-day drills.",
            "Capture drill evidence for auditing.",
            "Integrate post-incident feedback into runbook revisions.",
        ],
    },
]


def slugify(value: str) -> str:
    lowered = value.lower()
    lowered = re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")
    return lowered


def render_feature_doc(feature: dict) -> str:
    title = feature["feature"]
    score_a = feature["score_a"]
    score_b = feature["score_b"]
    confirmed = feature["confirmed_score"]
    lines = [
        f"# {title}",
        "",
        "## Audit scores",
        f"- Agent A score: **{score_a}%**",
        f"- Agent B score: **{score_b}%**",
        f"- Confirmed score (conservative): **{confirmed}%**",
        "",
        "## Agent A reviewed missing checklist",
    ]
    lines.extend([f"- [ ] {item}" for item in feature["agent_a_missing"]])
    lines.extend(["", "## Agent B reviewed missing checklist"])
    lines.extend([f"- [ ] {item}" for item in feature["agent_b_missing"]])
    lines.extend(["", "## Confirmed missing (both audits)"])
    lines.extend([f"- [ ] {item}" for item in feature["confirmed_missing"]])
    lines.extend(
        [
            "",
            "## Review method",
            "- [x] Independent auditor A review complete.",
            "- [x] Independent auditor B review complete.",
            "- [x] Conservative score set to minimum of both auditors.",
            "- [x] Confirmed-missing list created only from overlap themes.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_prompt_doc() -> str:
    return """# Production-grade prompt for repeatable final audits

Use this prompt when running a final, anti-inflation feature completion audit:

```text
You are an independent architecture completion auditor for this repository.
Task:
1) Audit ONLY the target feature list from docs/master-architecture-feature-completion.md.
2) Score each feature 0-100 using implementation evidence only (code/tests/runtime artifacts).
3) Treat documentation-only claims as 0 implementation credit.
4) Produce at least 8 atomic missing checklist items per feature.
5) Cite concrete file paths/symbols that justify any non-zero score.
6) Use conservative scoring. If uncertain, lower the score.
7) Return strict JSON:
{
  "features": [
    {
      "feature": "exact name",
      "score": 0-100,
      "implemented_evidence": ["..."],
      "missing_atomic": ["..."],
      "confidence": "high|medium|low"
    }
  ]
}
8) Never optimize to prior percentages. Recompute from repo evidence.
9) Flag mismatch where implementation contradicts current completion claims.
10) Do not stop at summaries; produce actionable atomic checklist items.
```
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for idx, feature in enumerate(FEATURES, start=1):
        slug = slugify(feature["feature"])
        path = OUT_DIR / f"{idx:02d}-{slug}.md"
        path.write_text(render_feature_doc(feature), encoding="utf-8")

    index_lines = [
        "# 2026-04-22 Scale feature audit (versioned)",
        "",
        "This folder contains one document per feature from the `Scale-out API and MCP/plugin platform features` section.",
        "Each feature doc includes:",
        "- two independent agent checklists (`Agent A`, `Agent B`),",
        "- conservative confirmed score (`min(agent_a, agent_b)`),",
        "- confirmed missing checklist reviewed as missing.",
        "",
        "## Feature docs",
    ]
    for idx, feature in enumerate(FEATURES, start=1):
        slug = slugify(feature["feature"])
        file_name = f"{idx:02d}-{slug}.md"
        index_lines.append(f"- `{file_name}`")
    index_lines.extend(
        [
            "",
            "## Validation",
            "- Run `python scripts/validate_scale_feature_audit.py`",
            "- Run `python -m pytest tests/docs/test_scale_feature_audit_validation.py`",
            "",
        ]
    )
    (OUT_DIR / "README.md").write_text("\n".join(index_lines), encoding="utf-8")
    (OUT_DIR / "production-grade-audit-prompt.md").write_text(
        render_prompt_doc(), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
